import Navbar from "@/components/Project/Navbar";
import ProjectSidebar from "@/components/Project/ProjectSidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <SidebarProvider>
          <ProjectSidebar />
          <SidebarInset className="flex flex-col">
            <Navbar />
            <main className="flex-1">{children}</main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
